### ISSUE TITLE
Is it  C++14 or  C++17?

### ISSUE THREAD

**Issue by moneroexamples** [0xdead4ead/beast_http_server#1]
Your readme says its C++14 but in CMakeLists.txt you require C++17?

**Comment by 0xdead4ead** [comment]
`if constexpr` available in с++17. Can be replaced with C ++ 14, in this case we get an extra warning

**Comment by moneroexamples** [comment]
Thanks for reply. Ok I will be checking it out. Your project seems as a good candidate to be viable alternative to https://github.com/ipkn/crow, though C++17 might be too new for many to use it.

I close this issue now, and if I have something new, I will make new one.

p.s.
good project, btw.
